- name: install supervisord
  apt: name=supervisor state=latest

- name: enable supervisord
  service: name=supervisor enabled=yes

- name: update supervisord.conf
  copy: src=supervisord.conf dest=/etc/supervisor/supervisord.conf

- name: restart supervisord
  service: name=supervisor state=restarted
