- name: update packages
  apt: upgrade=dist update_cache=yes state=latest

- name: install packages
  apt: name={{ item }} state=latest
  with_items:
    - rpi-update
    - cron-apt
    - iptables-persistent
    - sysv-rc-conf

- name: update firmware
  shell: rpi-update

- name: update auto update conf
  copy: src=3-download dest=/etc/cron-apt/action.d/3-download

- name: remove localtime
  file: path=/etc/localtime state=absent

- name: update localtime
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644

- name: update limits.conf
  copy: src=limits.conf dest=/etc/security/limits.conf

- name: update locale
  locale_gen: name=ja_JP.UTF-8 state=present

- name: update language
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.profile line="export LANG=ja_JP.UTF-8"

- name: update sysctl.conf
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes state=present reload=yes
  with_items:
    - {name: 'fs.file-max', value: '794573'}

- name: start ntpd
  service: name=ntp state=started enabled=yes

- name: update ntp servers
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntpd

- name: start iptables-persistent
  service: name=iptables-persistent state=started enabled=yes

- name: update iptable
  template: src=rules.v4.j2 dest=/etc/iptables/rules.v4
  notify: restart iptables-persistent

- name: update sshd config
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: restart sshd
