- name: remove localtime
  file: path=/etc/localtime state=absent

- name: update localtime
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644

- name: update limits.conf
  pam_limits: domain=joe limit_type=soft limit_item=nofile value=65536
  with_items:
    - { domain: "root", limit_type: "soft" }
    - { domain: "root", limit_type: "hard" }
    - { domain: "*", limit_type: "soft" }
    - { domain: "*", limit_type: "hard" }

- name: update locale
  locale_gen: name=ja_JP.UTF-8 state=present

- name: update language
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.profile line="export LANG=ja_JP.UTF-8"

- name: update sysctl.conf
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes state=present reload=yes
  with_items:
    - {name: 'fs.file-max', value: '794573'}
